# Site settings
title: Blog - Xiao Liu
description: "A blog for sharing thoughts on technology, science and insights at TheReviewIndex."
url: https://chriscliu.github.io/
homepage: http://xliu.info/
addr: http://blog.xliu.info/

github: https://github.com/ChrisCLiu/
author:
  name: "Xiao Liu"
  email: "chrisliu9603@gmail.com"
  url: "https://chriscliu.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/
port: 4002

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
